# ！/usr/bin/python3
# -*- coding: utf-8 -*-
# Copyright (c) 2017-2020 Rhilip <rhilipruan@gmail.com>

# Database
MYSQL_DATABASE_HOST = 'localhost'
MYSQL_DATABASE_PORT = 3306
MYSQL_DATABASE_USER = None
MYSQL_DATABASE_PASSWORD = None
MYSQL_DATABASE_DB = None
MYSQL_DATABASE_CHARSET = "utf8"
MYSQL_USE_UNICODE = True

# PT Gen
OMDB_API_KEY = ""

# PT Board
PTBOARD_SEARCH = ""
PTBOARD_SITE = ""
PTBOARD_NO_SITE = ""
PTBOARD_ORDER = "desc"
PTBOARD_LIMIT = 100
PTBOARD_OFFSET = 0
PTBOARD_START_TIME = 0
PTBOARD_END_TIME = "CURRENT_TIMESTAMP"
